import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { AutoSubmitForm } from "@/components/auto-submit-form";
import { EmptyState, PageHeader, SearchField } from "@/components/ui";
import { canonicalModels, catalog } from "@/lib/catalog";
import { compactNumber, formatPrice, priceRate } from "@/lib/format";
import { abilityMsg, msg } from "@/lib/i18n";
import { modelHref } from "@/lib/links";
import { getLocale } from "@/lib/server-i18n";

type Params = Promise<Record<string, string | string[] | undefined>>; const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";
export default async function ComparePage({ searchParams }: { searchParams: Params }) {
  const locale = await getLocale(); const params = await searchParams; const q = one(params.q).toLowerCase(); const owner = one(params.owner); const sort = one(params.sort) || "quality"; const ability = one(params.ability);
  const quality = canonicalModels.filter((model) => model.quality); const owners = [...new Set(quality.map((model) => model.ownerId))].sort(); const rows = quality.filter((model) => (!q || `${model.name} ${model.canonicalId}`.toLowerCase().includes(q)) && (!owner || model.ownerId === owner) && (!ability || model.abilities[ability])).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : (b.quality?.aaIndex ?? 0) - (a.quality?.aaIndex ?? 0)); const revision = catalog.sources.find((source) => source.id === "ai-pricing")?.revision;
  return <AppShell locale={locale} section={msg(locale, "compare")}><PageHeader title={msg(locale, "compare")} description={msg(locale, "qualityDescription")} /><AutoSubmitForm className="toolbar"><SearchField defaultValue={one(params.q)} placeholder={msg(locale, "searchModels")} /><select name="owner" defaultValue={owner} aria-label="Owner"><option value="">Owner</option>{owners.map((value) => <option key={value}>{value}</option>)}</select><select name="ability" defaultValue={ability} aria-label={msg(locale, "ability")}><option value="">{msg(locale, "allAbilities")}</option><option value="reasoning">{abilityMsg(locale, "reasoning")}</option><option value="toolCall">{abilityMsg(locale, "toolCall")}</option><option value="vision">{abilityMsg(locale, "vision")}</option></select><select name="sort" defaultValue={sort} aria-label="Sort"><option value="quality">AAIndex</option><option value="name">A–Z</option></select><Link href="/compare" className="text-button">{msg(locale, "reset")}</Link></AutoSubmitForm><div className="evidence-banner"><div><strong>{msg(locale, "qualityEvidence")}</strong><span>ai-pricing · {revision?.slice(0, 8) ?? "-"} · MIT</span></div><span>{quality.length} / {quality.length} {msg(locale, "mappedModels")}</span></div><div className="table-frame">{rows.length ? <table className="data-table compare-table"><thead><tr><th>{msg(locale, "model")}</th><th>AAIndex</th><th>USD Input</th><th>USD Output</th><th>CNY Input</th><th>CNY Output</th><th>{msg(locale, "context")}</th><th>{abilityMsg(locale, "toolCall")}</th><th>{abilityMsg(locale, "vision")}</th><th>{abilityMsg(locale, "reasoning")}</th></tr></thead><tbody>{rows.map((model) => <tr key={model.canonicalId}><td className="entity-cell"><Link className="entity-name" href={modelHref(model.canonicalId)}>{model.name}<small>{model.canonicalId}</small></Link></td><td><div className="quality-cell"><span className="bar"><i style={{ width: `${Math.min(100, (model.quality?.aaIndex ?? 0) * 2)}%` }} /></span><b>{model.quality?.aaIndex}</b></div></td><td className="mono">{formatPrice(priceRate(model.minPrices.USD, "textInput"), "USD")}</td><td className="mono">{formatPrice(priceRate(model.minPrices.USD, "textOutput"), "USD")}</td><td className="mono">{formatPrice(priceRate(model.minPrices.CNY, "textInput"), "CNY")}</td><td className="mono">{formatPrice(priceRate(model.minPrices.CNY, "textOutput"), "CNY")}</td><td className="mono">{compactNumber(model.contextWindow)}</td><td className={model.abilities.toolCall ? "yes" : "no"}>{model.abilities.toolCall ? "✓" : "-"}</td><td className={model.abilities.vision ? "yes" : "no"}>{model.abilities.vision ? "✓" : "-"}</td><td className={model.abilities.reasoning ? "yes" : "no"}>{model.abilities.reasoning ? "✓" : "-"}</td></tr>)}</tbody></table> : <EmptyState>{msg(locale, "noResults")}</EmptyState>}<div className="table-footer"><span>{rows.length} / {quality.length} {msg(locale, "mappedModels")}</span></div></div></AppShell>;
}
