/**
 * Board registry for data/model-index.json.
 * Every board must be public, free, and refreshable without credentials.
 * `direction` tells the UI whether a higher score is better.
 */
export const MODEL_INDEX_BOARD_CONFIG = {
  aaindex: {
    id: "aaindex",
    name: "AAIndex",
    label: { zh: "AAIndex 综合", en: "AAIndex" },
    kind: "quality",
    metric: "aaIndex",
    direction: "higher",
    sourceId: "ai-pricing",
    sourceName: "ai-pricing (Artificial Analysis mirror)",
    homepageUrl: "https://github.com/nuxdie/ai-pricing",
    license: "MIT",
    note: { zh: "沿用 models.json 内已有的 AAIndex 证据，未二次存储。", en: "Projected from the AAIndex evidence already stored in models.json." },
  },
  "lmarena-text": {
    id: "lmarena-text",
    name: "LMArena Elo",
    label: { zh: "Arena Elo（文本）", en: "Arena Elo (text)" },
    kind: "arena",
    metric: "arenaScore",
    direction: "higher",
    sourceId: "lmarena-leaderboard-dataset",
    sourceName: "LM Arena 官方排行榜数据集 (HuggingFace)",
    homepageUrl: "https://arena.ai/leaderboard",
    sourceUrl: "https://huggingface.co/datasets/lmarena-ai/leaderboard-dataset",
    license: "CC-BY-4.0",
    huggingface: { repo: "lmarena-ai/leaderboard-dataset", ref: "main", path: "text/latest-00000-of-00001.parquet" },
    note: { zh: "人类盲测胜率换算的 Elo 分与投票数，数据来自 LM Arena 官方数据集（CC-BY-4.0）。", en: "Elo derived from blind human pairwise votes. Data from LM Arena official dataset (CC-BY-4.0)." },
  },
  "lmarena-vision": {
    id: "lmarena-vision",
    name: "LMArena Vision Elo",
    label: { zh: "Arena Elo（视觉）", en: "Arena Elo (vision)" },
    kind: "arena",
    metric: "arenaScore",
    direction: "higher",
    sourceId: "lmarena-leaderboard-dataset",
    sourceName: "LM Arena 官方排行榜数据集 (HuggingFace)",
    homepageUrl: "https://arena.ai/leaderboard/vision",
    sourceUrl: "https://huggingface.co/datasets/lmarena-ai/leaderboard-dataset",
    license: "CC-BY-4.0",
    huggingface: { repo: "lmarena-ai/leaderboard-dataset", ref: "main", path: "vision/latest-00000-of-00001.parquet" },
  },
  "aider-polyglot": {
    id: "aider-polyglot",
    name: "Aider Polyglot",
    label: { zh: "Aider 编码", en: "Aider Polyglot" },
    kind: "coding",
    metric: "passRate",
    direction: "higher",
    sourceId: "aider",
    sourceName: "Aider polyglot coding leaderboard",
    homepageUrl: "https://aider.chat/docs/leaderboards/",
    repository: "https://github.com/Aider-AI/aider",
    license: "Apache-2.0",
    github: { repository: "Aider-AI/aider", ref: "main", path: "aider/website/_data/polyglot_leaderboard.yml" },
    note: { zh: "多语言代码编辑通过率（pass_rate_2）。", en: "Multi-language code editing pass rate (pass_rate_2)." },
  },
  "hf-downloads": {
    id: "hf-downloads",
    name: "Hugging Face downloads",
    label: { zh: "HF 近 30 天下载", en: "HF 30-day downloads" },
    kind: "popularity",
    metric: "downloads30d",
    direction: "higher",
    sourceId: "huggingface",
    sourceName: "Hugging Face Hub API",
    homepageUrl: "https://huggingface.co/models?pipeline_tag=text-generation&sort=downloads",
    license: "Hub public metadata",
    match: { ownerRequired: true, allowLoose: false },
    note: { zh: "开源权重模型的真实拉取热度，闭源模型天然为空。", en: "Real pull volume for open-weight models; closed models stay blank." },
  },
};

export const HUGGING_FACE_CRAWL = {
  endpoint: "https://huggingface.co/api/models",
  pipelineTags: ["text-generation", "image-text-to-text"],
  pageSize: 500,
  maxPages: 6,
};
