import { ChevronRight } from "lucide-react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { AutoSubmitForm } from "@/components/auto-submit-form";
import { TableRowLink } from "@/components/table-row-link";
import { EmptyState, MetricStrip, PageHeader, Pagination, SearchField } from "@/components/ui";
import { catalog, providerStats } from "@/lib/catalog";
import { compactNumber } from "@/lib/format";
import { msg } from "@/lib/i18n";
import { getLocale } from "@/lib/server-i18n";

const PAGE_SIZE = 20;
type Params = Promise<Record<string, string | string[] | undefined>>;
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";
export default async function ProvidersPage({ searchParams }: { searchParams: Params }) {
  const locale = await getLocale(); const params = await searchParams; const q = one(params.q).toLowerCase(); const kind = one(params.kind); const currency = one(params.currency); const sort = one(params.sort) || "models"; const page = Math.max(1, Number(one(params.page)) || 1);
  const enriched = catalog.providers.map((provider) => ({ provider, stats: providerStats(provider) })).filter(({ provider, stats }) => (!q || `${provider.name} ${provider.id}`.toLowerCase().includes(q)) && (!kind || (kind === "official" ? provider.official : provider.featured)) && (!currency || (currency === "USD" ? stats.usdCount : stats.cnyCount))).sort((a, b) => sort === "name" ? a.provider.name.localeCompare(b.provider.name) : b.stats.modelCount - a.stats.modelCount);
  const pages = Math.max(1, Math.ceil(enriched.length / PAGE_SIZE)); const current = Math.min(page, pages); const rows = enriched.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);
  const linkFor = (next: number) => { const query = new URLSearchParams(); for (const key of ["q", "kind", "currency", "sort"] as const) { const value = one(params[key]); if (value) query.set(key, value); } query.set("page", String(next)); return `/providers?${query}`; };
  return <AppShell locale={locale} section={msg(locale, "providers")}><PageHeader title={msg(locale, "providers")} description={msg(locale, "providerDescription")} /><AutoSubmitForm className="toolbar"><SearchField defaultValue={one(params.q)} placeholder={msg(locale, "searchProviders")} /><select name="kind" defaultValue={kind} aria-label="Provider type"><option value="">{locale === "zh" ? "全部类型" : "All types"}</option><option value="official">{msg(locale, "officialProviders")}</option><option value="featured">{msg(locale, "featuredProviders")}</option></select><select name="currency" defaultValue={currency} aria-label={msg(locale, "currency")}><option value="">{msg(locale, "allCurrencies")}</option><option>USD</option><option>CNY</option></select><select name="sort" defaultValue={sort} aria-label="Sort"><option value="models">{msg(locale, "modelCount")}</option><option value="name">A–Z</option></select><Link href="/providers" className="text-button">{msg(locale, "reset")}</Link></AutoSubmitForm><MetricStrip metrics={[{ value: catalog.providers.length, label: msg(locale, "providerCount") },{ value: catalog.providers.filter((provider) => provider.official).length, label: msg(locale, "officialProviders") },{ value: catalog.providers.filter((provider) => provider.enabled !== false).length, label: msg(locale, "enabledProviders") },{ value: catalog.providers.filter((provider) => provider.featured).length, label: msg(locale, "featuredProviders") }]} /><div className="table-frame">{rows.length ? <table className="data-table"><thead><tr><th>{msg(locale, "providers")}</th><th>API</th><th>{msg(locale, "modelCount")}</th><th>USD</th><th>CNY</th><th>Quality</th><th /></tr></thead><tbody>{rows.map(({ provider, stats }) => <TableRowLink key={provider.id} href={`/providers/${encodeURIComponent(provider.id)}`} label={`${msg(locale, "details")}: ${provider.name}`}><td className="entity-cell"><Link className="entity-name" href={`/providers/${encodeURIComponent(provider.id)}`}>{provider.name}<small>{provider.id}</small></Link></td><td><div className="tag-list">{provider.official && <span className="tag success">Official</span>}{provider.api && <span className="tag">{provider.api}</span>}</div></td><td className="mono">{stats.modelCount}</td><td className="mono">{stats.usdCount}</td><td className="mono">{stats.cnyCount}</td><td className="mono">{stats.qualityCount}</td><td><ChevronRight size={15} /></td></TableRowLink>)}</tbody></table> : <EmptyState>{msg(locale, "noResults")}</EmptyState>}<div className="table-footer"><span>{compactNumber(enriched.length)} {msg(locale, "providers")}</span><Pagination page={current} pages={pages} href={linkFor} /></div></div></AppShell>;
}
